const {chromium}=require('playwright');
const path=require('node:path');
const assert=require('node:assert/strict');
const dir=path.resolve(__dirname,'../artifacts');
const origin='http://localhost:8081';
const campus='梧桐大学 · 联测'+String(Date.now()).slice(-6);
async function screenshot(p,name){await p.mouse.move(0,0);await p.waitForTimeout(700);await p.screenshot({path:path.join(dir,name)});}
async function api(method,route,token,data){const r=await fetch(origin+'/api/v1'+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:data?JSON.stringify(data):undefined});const payload=r.status===204?null:await r.json();if(!r.ok)throw Error(JSON.stringify(payload));return payload;}
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
 const p=await browser.newPage({viewport:{width:390,height:844}});
 const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://localhost:8090');await p.waitForSelector('flutter-view');
 const placeholder=p.locator('flt-semantics-placeholder');await placeholder.waitFor();await placeholder.evaluate(e=>e.click());
 p.setDefaultTimeout(15000);
 await p.getByRole('textbox',{name:'你在哪所学校？'}).fill(campus);
 await p.getByRole('checkbox').check();
 await p.getByRole('button',{name:'进入校园'}).click();
 await p.getByText('校园里的声音',{exact:true}).waitFor({timeout:20000});
 await screenshot(p,'android-square-empty.png');
 console.log('JOIN PASS');
 const other=await api('POST','/session',null,{campus});
 await api('PATCH','/me',other.token,{alias:'晚风里的小猫'});
 const post=await api('POST','/posts',other.token,{body:'今天绕了远路回宿舍，才发现学校的晚霞这么好看。\n偶尔慢一点，好像也没关系。',category:'校园日常'});
 await api('POST','/posts',other.token,{body:'想找一个每周一起去图书馆的搭子，不用聊天，各自努力就好。有人一起吗？',category:'搭子集合'});
 await p.getByRole('button',{name:'刷新广场'}).click();
 await p.getByRole('group',{name:/今天绕了远路回宿舍/}).waitFor();
 await screenshot(p,'android-square.png');
 console.log('FEED PASS');
 await p.getByRole('group',{name:/今天绕了远路回宿舍/}).click({position:{x:100,y:80}});
 await p.getByRole('textbox').fill('我也是，慢一点也很好。');
 await p.getByRole('button',{name:'发送评论'}).click();
 await p.getByText('我也是，慢一点也很好。').waitFor();
 assert((await api('GET','/posts/'+post.id+'/comments',other.token)).some(c=>c.body==='我也是，慢一点也很好。'));
 console.log('COMMENT PERSISTED PASS');
 await p.getByRole('button',{name:'悄悄打个招呼'}).click();
 await p.getByText('匿名私聊 · 保护彼此的边界').waitFor();
 await p.getByRole('textbox').fill('你好呀，看到你的晚霞分享了。');
 await p.getByRole('button',{name:'发送消息'}).click();
 await p.getByText('你好呀，看到你的晚霞分享了。').waitFor();
 const conversations=await api('GET','/conversations',other.token);
 const conv=conversations.find(c=>c.lastMessage==='你好呀，看到你的晚霞分享了。');assert(conv);
 await api('POST','/conversations/'+conv.id+'/messages',other.token,{body:'好巧！希望你今天也有一个好心情。'});
 await p.getByText('好巧！希望你今天也有一个好心情。').waitFor({timeout:10000});
 await screenshot(p,'android-chat.png');
 console.log('TWO-USER CHAT PASS');
 await p.getByRole('button',{name:'Back',exact:true}).click();
 await p.getByRole('button',{name:'Back',exact:true}).click();
 await p.getByRole('tab',{name:'房间',exact:true}).click();
 await p.getByText('深夜树洞').waitFor();
 await p.waitForTimeout(600);
 await screenshot(p,'android-rooms.png');
 await p.getByText('深夜树洞').click();
 await p.getByRole('textbox').fill('今晚想把烦恼暂时放下，明天再认真生活。');
 await p.getByRole('button',{name:'发送消息'}).click();
 await p.getByText('今晚想把烦恼暂时放下，明天再认真生活。').waitFor();
 assert((await api('GET','/rooms/treehole/messages',other.token)).some(m=>m.body==='今晚想把烦恼暂时放下，明天再认真生活。'));
 console.log('ROOM MESSAGE PERSISTED PASS');
 await p.getByRole('button',{name:'Back',exact:true}).click();
 await p.waitForTimeout(600);
 await p.getByRole('tab',{name:'我的',exact:true}).click();
 await p.waitForTimeout(700);
 await p.getByText('修改匿名昵称').click();
 await p.getByRole('textbox').fill('慢慢生长的小树');
 await p.getByRole('button',{name:'保存',exact:true}).click();
 await p.getByText('慢慢生长的小树').waitFor();
 await screenshot(p,'android-profile.png');
 const darkSwitch=p.getByRole('switch').nth(1);
 await darkSwitch.click();
 await p.waitForFunction(()=>document.querySelectorAll('[role="switch"]')[1]?.getAttribute('aria-checked')==='true');
 await p.waitForTimeout(500);
 await screenshot(p,'android-profile-dark.png');
 await darkSwitch.click();
 await p.waitForFunction(()=>document.querySelectorAll('[role="switch"]')[1]?.getAttribute('aria-checked')==='false');
 await p.waitForTimeout(500);
 console.log('DARK MODE PASS');
 await p.getByRole('tab',{name:'广场',exact:true}).click();
 await p.waitForTimeout(600);
 await p.getByRole('button',{name:'说点什么',exact:true}).click();
 await p.getByRole('textbox').fill('今天的第一条声音：谢谢陌生人的温柔回应。');
 await p.getByRole('button',{name:'发布',exact:true}).click();
 await p.getByRole('group',{name:/今天的第一条声音/}).waitFor();
 assert((await api('GET','/posts',other.token)).some(m=>m.body==='今天的第一条声音：谢谢陌生人的温柔回应。'&&m.alias==='慢慢生长的小树'));
 console.log('UI POST AND PROFILE PERSISTED PASS');
 await p.setViewportSize({width:1440,height:1000});
 await p.waitForTimeout(700);
 await screenshot(p,'desktop-app.png');
 console.log('ROOMS PROFILE DESKTOP PASS');
 assert.deepEqual(errors,[]);
 }finally{await browser.close();}
})();
